#!/bin/bash

test_server_stdout=tests/server.stdout

function install_deps {
    if [ -z "$GITHUB_ACTIONS" ]; then
        poetry install
    else
        echo "Skipping dependency installation on GitHub Actions"
    fi
}

function start_server {
    rm -f ${test_server_stdout}
    poetry run python tests/m3u8server.py >${test_server_stdout} 2>&1 &
}

function stop_server {
    pkill -9 -f m3u8server.py
    echo "Test server stdout on ${test_server_stdout}"
}

function run {
    poetry run pytest -vv --cov-report term-missing --cov m3u8 tests/
}

function main {
    install_deps
    start_server
    run
    retval=$?
    stop_server
    return "$retval"
}

if [ -z "$1" ]; then
    main
else
    "$@"
fi
